### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by madanvaidya007** [Pinqua/Zinger#1]
Where i admin login

**Comment by Pinqua** [comment]
If you have connected with MongoDB then in that there will be an admin table in which you can add an email ID through which you want to login as an admin. After this, you will see the dashboard option in the dropdown and sidebar. I have also attached a screenshot for your ref.
![Screenshot from 2022-08-02 16-16-32](https://user-images.githubusercontent.com/69719134/182356880-d13b94f1-2a21-4e4e-8d1a-bb4faca0e61d.png)

**Comment by eugene254-ship-it** [comment]
It's not bringing down the Dashboard. I have followed all the steps
