### ISSUE TITLE
Admin panel access

### ISSUE THREAD

**Issue by eugene254-ship-it** [Pinqua/Zinger#2]
How to access the admin panel to add products

**Comment by Pinqua** [comment]
add you email id inside admin collection in mongodb and try login in with
same email id you will see dashboard option

Refer this issue - https://github.com/Pinqua/Zinger/issues/1

**Comment by programmer22** [comment]
I don't have an admin collection and I did everything correctly from installing the project to doing yarn install and yarn dev. Products aren't loading into Mongodb from dishes.json and the admin collection doesn't show.

**Comment by eugene254-ship-it** [comment]
👀👀was this solved
